management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 1234
spring:
  application:
    name: WELCOME-API
  boot:
    admin:
      client:
        url: http://localhost:9999/
